POST http://maxerdan-001-site1.itempurl.com/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJuYmYiOjE2Mzg0NjM1ODgsImV4cCI6MTYzOTA2ODM4NywiaWF0IjoxNjM4NDYzNTg4fQ.xlFd2UlU2pwkTmE6vavss09ZXgO-lhk187J_9dM2yCQ
