# Generated by Django 3.2.8 on 2021-10-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20211018_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='scripts_id',
            new_name='script_id',
        ),
    ]
