# Generated by Django 3.2.8 on 2021-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_rename_scripts_id_script_script_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='id',
        ),
        migrations.AlterField(
            model_name='script',
            name='script_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
