# Generated by Django 3.2.8 on 2021-11-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20211018_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='endAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='linkList',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('startId', models.CharField(max_length=255)),
                ('endId', models.CharField(max_length=255)),
                ('meta', models.CharField(default=None, max_length=255)),
                ('endAt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.endat')),
            ],
        ),
        migrations.CreateModel(
            name='meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='nodeList',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.coordinate')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.meta')),
            ],
        ),
        migrations.CreateModel(
            name='origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='startAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.AddField(
            model_name='linklist',
            name='startAt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.startat'),
        ),
    ]
